//
//  ApodInteractor.swift
//  spaceApp
//
//  Created by Coldefy Yoann on 2016/07/17.
//  Copyright (c) 2016年 YoannColdefy. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

protocol ApodInteractorInput {
	func fetchTodayApod(request: TodayApodRequest)
	func fetchRandomApod(request: RandomApodRequest)
}

protocol ApodInteractorOutput {
	func presentApod(response: ApodResponse)
	func presentError(response: ApodErrorResponse)
}

class ApodInteractor: ApodInteractorInput {
	var output: ApodInteractorOutput!
	private var _apodWorker: ApodWorker
	private var _pictureDownloadWorker: PictureDownloadWorker
	
	init(apodWorker: ApodWorker, pictureDownloadWorker: PictureDownloadWorker) {
		_apodWorker = apodWorker
		_pictureDownloadWorker = pictureDownloadWorker
	}
	
	// MARK: Business logic
	func fetchTodayApod(request: TodayApodRequest) {
		_apodWorker.fetchTodayAPOD() {
			apodData, error in
			self.handleFetchResults(apodData: apodData, error: error)
		}
	}

	func fetchRandomApod(request: RandomApodRequest) {
		_apodWorker.fetchRandomApod() {
			apodData, error in
			self.handleFetchResults(apodData: apodData, error: error)
		}
	}
	
	private func handleFetchResults(apodData: ApodData?, error: NSError?) {
		if let apodData = apodData {
			let response = ApodResponse(apodData: apodData)
			self.output.presentApod(response: response)
			
			let url: URL
			if let hdUrl = apodData.hdUrl {
				url = hdUrl
			} else {
				url = apodData.url
			}
			
			_pictureDownloadWorker.downolad(url: url, progressHandler: {_ in}, completionHandler: {_,_ in})
			
		}
		
		if let error = error {
			let response = ApodErrorResponse(error: error)
			self.output.presentError(response: response)
		}
	}
}
