//
//  ApodInteractor.swift
//  spaceApp
//
//  Created by Coldefy Yoann on 2016/07/17.
//  Copyright (c) 2016年 YoannColdefy. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

protocol ApodInteractorInput {
	func fetchTodayApod(request: TodayApodRequest)
}

protocol ApodInteractorOutput {
	func presentApod(response: ApodResponse)
	func presentError(response: ApodErrorResponse)
}

class ApodInteractor: ApodInteractorInput {
	var output: ApodInteractorOutput!
	private var _apodWorker: ApodWorker
	
	init(apodWorker: ApodWorker) {
		_apodWorker = apodWorker
	}
	
	// MARK: Business logic
	func fetchTodayApod(request: TodayApodRequest) {
		_apodWorker.fetchTodayAPOD() {
			data, error in
			if let data = data {
				let response = ApodResponse(apodData: data)
				self.output.presentApod(response: response)
			}
			
			if let error = error {
				let response = ApodErrorResponse(error: error)
				self.output.presentError(response: response)
			}
		}
	}
//	func doSomething(request: ApodRequest) {
//		// NOTE: Create some Worker to do the work
//		
//		worker = ApodWorker()
//		worker.doSomeWork()
//		
//		// NOTE: Pass the result to the Presenter
//		
//		let response = ApodResponse()
//		output.presentSomething(response)
//	}
}
