//
//  ApodModels.swift
//  spaceApp
//
//  Created by Coldefy Yoann on 2016/07/17.
//  Copyright (c) 2016年 YoannColdefy. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

struct TodayApodRequest {
}

struct RandomApodRequest {

}

struct ApodResponse {
	var apodData: ApodData
}

struct ApodErrorResponse {
	var error: Error
}

struct ApodPictureDownloadProgressResponse {
	var progressRatio: Double
}

struct ApodPictureResponse {
	var picture: UIImage
}

struct ApodDataViewModel {
	var title: String
	var text: String
}

struct ApodImageViewModel {
	var picture: UIImage?
}

struct ApodPictureDownloadProgressViewModel {
	var progressRatio: Float
}

struct ApodErrorViewModel {
	var errorMessage: String
}
