//
//  ApodPresenter.swift
//  spaceApp
//
//  Created by Coldefy Yoann on 2016/07/17.
//  Copyright (c) 2016年 YoannColdefy. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

import UIKit

protocol ApodPresenterInput {
	func presentApod(response: ApodResponse)
	func presentError(response: ApodErrorResponse)
}

protocol ApodPresenterOutput: class {
	func displayApod(viewModel: ApodViewModel)
	func displayApodError(viewModel: ApodErrorViewModel)
}

class ApodPresenter: ApodPresenterInput {
	weak var output: ApodPresenterOutput!
	
	// MARK: Presentation logic
	
	func presentApod(response: ApodResponse) {
		let viewModel = makeApodViewModel(apodData: response.apodData) 
		
		output.displayApod(viewModel: viewModel)
	}
	
	private func makeApodViewModel(apodData: ApodData) -> ApodViewModel {
		let title = apodData.title
		let date = dateToString(date: apodData.date)
		let explanation = apodData.explanation
		let copyright = apodData.copyright
		let picture = loadImage(url: apodData.hdUrl)
		
		return ApodViewModel(title: title, picture: picture, date: date, explanation: explanation, copyright: copyright)
	}
	
	private func dateToString(date: Date) -> String {
		let formatter = DateFormatter()
		formatter.dateFormat = "yyyy年MM月dd日"
		return formatter.string(from: date)
	}
	
	private func loadImage(url: URL) -> UIImage? {
		guard let data = try? Data(contentsOf: url) else {
			return nil
		}
		
		return UIImage(data: data)
	}
	
	func presentError(response: ApodErrorResponse) {
		let viewModel = ApodErrorViewModel(errorMessage: response.error.localizedDescription)
		output.displayApodError(viewModel: viewModel)
	}
	
}
