//
//  ApodPresenterTests.swift
//  spaceApp
//
//  Created by Coldefy Yoann on 2016/07/17.
//  Copyright (c) 2016年 YoannColdefy. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

@testable import spaceApp
import XCTest

class ApodPresenterTests: XCTestCase {
	// MARK: Subject under test
	
	var sut: ApodPresenter!
	
	// MARK: Test lifecycle
	
	override func setUp() {
		super.setUp()
		setupApodPresenter()
	}
	
	override func tearDown() {
		super.tearDown()
	}
	
	// MARK: Test setup
	
	func setupApodPresenter() {
		sut = ApodPresenter()
	}
	
	// MARK: Test doubles
	
	// MARK: Tests
	
	func testSomething() {
		// Given
		
		// When
		
		// Then
	}
}
