//
//  ApodInteractorTests.swift
//  spaceApp
//
//  Created by Coldefy Yoann on 2016/07/17.
//  Copyright (c) 2016年 YoannColdefy. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so you can apply
//  clean architecture to your iOS and Mac projects, see http://clean-swift.com
//

@testable import spaceApp
import XCTest

class ApodInteractorTests: XCTestCase {
	// MARK: Subject under test
	var target: ApodInteractor!
	var mochApodWorker: MockApodWorker!
}

// MARK: Test lifecycle
extension ApodInteractorTests {
	override func setUp() {
		super.setUp()
		setupApodInteractor()
	}
	
	override func tearDown() {
		super.tearDown()
	}
}

// MARK: Test setup
extension ApodInteractorTests {
	func setupApodInteractor() {
		mochApodWorker = MockApodWorker()
		target = ApodInteractor(apodWorker: mochApodWorker)
	}
}

// MARK: Test doubles
extension ApodInteractorTests {
	class MockApodStore: ApodStore {
		func fetchPictureFor(date: Date, completionHandler: ApodCompletionHandler) {
			
		}
		
		func fetchTodaysPicture(completionHandler: ApodCompletionHandler) {
			
		}
	}
	
	class MockApodWorker: ApodWorker {
		var fetchTodayApodCalled = false
		
		init() {
			super.init(apodStore: MockApodStore())
		}
		
		override func fetchTodayAPOD(completionHandler: (apodData: ApodData?, error: NSError?) -> Void) {
			fetchTodayApodCalled = true
		}
	}
}

// MARK: Tests
extension ApodInteractorTests {
	func test_fetchTodayApod_callsTheOutputShowDevice() {
		// Arrange
		let request = TodayApodRequest()
		
		// Act
		target.fetchTodayApod(request: request)
		
		// Assert
		XCTAssertTrue(mochApodWorker.fetchTodayApodCalled)
		
	}
}
